// <auto-generated />
using System;
using DesafioVWFS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DesafioVWFS.Migrations
{
    [DbContext(typeof(DesafioDbContext))]
    [Migration("20260715235729_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DesafioVWFS.Application.Shared.Domain.Entities.Contrato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_contrato");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("fl_ativo");

                    b.Property<string>("ClienteCpfCnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)")
                        .HasColumnName("nr_cpf_cnpj_cliente");

                    b.Property<int>("CondicaoVeiculo")
                        .HasColumnType("integer")
                        .HasColumnName("tp_condicao_veiculo");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dh_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dh_criacao")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DataVencimentoPrimeiraParcela")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_vencimento_primeira_parcela");

                    b.Property<int>("PrazoMeses")
                        .HasColumnType("integer")
                        .HasColumnName("qt_prazo_meses");

                    b.Property<decimal>("TaxaMensal")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("pc_taxa_mensal");

                    b.Property<int>("TipoVeiculo")
                        .HasColumnType("integer")
                        .HasColumnName("tp_veiculo");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("vl_total");

                    b.HasKey("Id");

                    b.HasIndex("Ativo")
                        .HasDatabaseName("ix_tb_contratos_fl_ativo");

                    b.HasIndex("ClienteCpfCnpj")
                        .HasDatabaseName("ix_tb_contratos_nr_cpf_cnpj_cliente");

                    b.ToTable("tb_contratos", (string)null);
                });

            modelBuilder.Entity("DesafioVWFS.Application.Shared.Domain.Entities.Pagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_pagamento");

                    b.Property<decimal>("Amortizacao")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("vl_amortizacao");

                    b.Property<Guid>("ContratoId")
                        .HasColumnType("uuid")
                        .HasColumnName("id_contrato");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dh_criacao")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_pagamento");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_vencimento");

                    b.Property<decimal>("Juros")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("vl_juros");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ds_observacao");

                    b.Property<decimal>("SaldoDevedor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("vl_saldo_devedor");

                    b.Property<int>("StatusPagamento")
                        .HasColumnType("integer")
                        .HasColumnName("st_pagamento");

                    b.Property<decimal>("ValorParcela")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("vl_parcela");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId")
                        .HasDatabaseName("ix_tb_pagamentos_id_contrato");

                    b.HasIndex("DataVencimento")
                        .HasDatabaseName("ix_tb_pagamentos_dt_vencimento");

                    b.ToTable("tb_pagamentos", (string)null);
                });

            modelBuilder.Entity("DesafioVWFS.Application.Shared.Domain.Entities.Pagamento", b =>
                {
                    b.HasOne("DesafioVWFS.Application.Shared.Domain.Entities.Contrato", "Contrato")
                        .WithMany("Pagamentos")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contrato");
                });

            modelBuilder.Entity("DesafioVWFS.Application.Shared.Domain.Entities.Contrato", b =>
                {
                    b.Navigation("Pagamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
